### ISSUE TITLE
Bios 0056 is available now

### ISSUE THREAD

**Issue by DWomack** [hackintosh-efi/intel-nuc10#60]
As of March 17, 2022.

**Comment by HawkysCC** [comment]
The newest version 0056 will make CFGLock.efi unable to work,DO NOT UPDATE.

**Comment by DWomack** [comment]
Thank you for the heads up.

**Comment by DWomack** [comment]
Installed .80 without issue with 0055 BIOS. 

Thanks

**Comment by gtrooper** [comment]
Can someone please upload BIOS 0055 ? Intel removed it from their site ! Thanks !

**Comment by DWomack** [comment]
Search GitHub for mackonsti. 

He seems to have it archived in his code section.

**Comment by essereio** [comment]
https://github.com/mackonsti/nuc10i7fnh/tree/master/BIOS

**Comment by stoivo** [comment]
Anybody know if Bios 0057 will work?

**Comment by essereio** [comment]
> Anybody know if Bios 0057 will work?

I decided to test it. It boots into MacOS however unsure yet regarding long term system stability. I initially experienced 300%+ high CPU usage with mds_stores but it's stable now.

FYI. I also never press the enter key while at the Opencore boot screen because MacOS would have issues booting in the past. Unsure if this is still an issue with Opencore.
