### ISSUE TITLE
[MacOS Ventura] issue with mic jack 3.5 mm

### ISSUE THREAD

**Issue by SalvatoreAD** [hackintosh-efi/intel-nuc10#90]
Hello and congratulations on the project. I'm having trouble getting my headset to work. the audio is heard correctly, but the microphone is not shown in the audio configuration. Can you help me?

I'm using last release of EFI.

**Comment by essereio** [comment]
The Microphone doesn't work through the headset but the front 4 microphones (Internal Microphone in audio settings) work very well.

You'll need the following adapter if you want to use the headset microphone. It's available on amazon. JSAUX brand is the best one available and I've had the adapter since June without any issues.

https://www.google.com/search?q=JSAUX+USB+Type+C+to+3.5mm+Female+Headphone+Jack+Adapter
